### ISSUE TITLE
Stop working in production 

### ISSUE THREAD

**Issue by damienmasson** [unverbuggt/mkdocs-encryptcontent-plugin#40]
Hi, everything worked fine until I made a recent update of my website. It still work when testing with `mkdocs serve`, but does not work on generated site after a `mkdocs build`. 

Does not work means that the page keep continue to ask the password instead of decrypt the content.

I set up a very simple empty new project to expose the issue.
The result is here : http://igm.univ-mlv.fr/~masson/site/

The mkdocs.yml file: 
```
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Docs
theme:
  name: material

nav:
  - index.md
  - protected.md


plugins:
  - search: {}
  - encryptcontent: {}
```

and the content of the file protected.md:
```
---
password: pwd
---

this page is protected!
```

My mkdocs version:
`mkdocs, version 1.4.2 from /home/dm/.local/lib/python3.10/site-packages/mkdocs (Python 3.10)`

Any ideas ?

**Comment by unverbuggt** [comment]
Hi,

the current release (2.3.1) will fail to build in combination with mkdocs 1.4, because they changed the class of "PluginCollection". Error Message: `AttributeError: 'PluginCollection' object has no attribute 'move_to_end'`

This [patch](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/commit/36f63ba21763361de4ce269a4fa3b2e965d5a9b9) silences the error and simply displays a waring to move search and encryptcontetn to the end of the plugins list.  
Apply the patch manually or use the current development version.

Your demo site (at http://igm.univ-mlv.fr/~masson/site/protected/) tries to download the file: https://igm.univ-gustave-eiffel.fr/assets/javascripts/decrypt-contents.js which it cannot find.

**Comment by damienmasson** [comment]
Great, adding the site_url: to the yml fixed the issue !
thanks a lot.
